### ISSUE TITLE
关于依赖的包的问题

### ISSUE THREAD

**Issue by myccver** [AcherStyx/Compressed-Video-Reader#1]
您好，我想请问在之前已经安装过ffmpeg的前提下，Compressed-Video-Reader/ffmpeg/install_ffmpeg.sh中的
sudo apt -y install \
    libass-dev \
    libfreetype6-dev \
    libsdl2-dev \
    libtool \
    libva-dev \
    libvdpau-dev \
    libvorbis-dev \
    libxcb1-dev \
    libxcb-shm0-dev \
    libxcb-xfixes0-dev \
    texinfo \
    zlib1g-dev \
    nasm \
    yasm \
    libx264-dev \
    libx265-dev \
    libnuma-dev \
    libvpx-dev \
    libmp3lame-dev \
    libopus-dev
    可以注释掉吗？毕竟这个命令需要root权限

**Comment by Yaojie-Shen** [comment]
> 您好，我想请问在之前已经安装过ffmpeg的前提下，Compressed-Video-Reader/ffmpeg/install_ffmpeg.sh中的 sudo apt -y install libass-dev libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev texinfo zlib1g-dev nasm yasm libx264-dev libx265-dev libnuma-dev libvpx-dev libmp3lame-dev libopus-dev 可以注释掉吗？毕竟这个命令需要root权限

不确定，可以试试……
我还在计划着发布到pypi上（这样就不需要本地编译了），但是由于环境的问题暂时搁置了。如果是因为没有办法获得权限的话你可以试着在你有权限的linux环境下先编译出一个whl文件，正确的情况下应该会有100MB以上的大小，然后上传到你目前的系统上安装。

**Comment by myccver** [comment]
> > 您好，我想请问在之前已经安装过ffmpeg的前提下，Compressed-Video-Reader/ffmpeg/install_ffmpeg.sh中的 sudo apt -y install libass-dev libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev texinfo zlib1g-dev nasm yasm libx264-dev libx265-dev libnuma-dev libvpx-dev libmp3lame-dev libopus-dev 可以注释掉吗？毕竟这个命令需要root权限
> 
> 不确定，可以试试…… 我还在计划着发布到pypi上（这样就不需要本地编译了），但是由于环境的问题暂时搁置了。如果是因为没有办法获得权限的话你可以试着在你有权限的linux环境下先编译出一个whl文件，正确的情况下应该会有100MB以上的大小，然后上传到你目前的系统上安装。

好的，非常感谢您的回复。另外我想问下论文中提到的fast是指inference的时候吗？类似swinbert这种end-to-end模型，您论文中设计的模型train过程似乎并不快。使用离线特征训练模型的话，只需要预训练模型抽取一次特征，但是训练起来快很多(这对于调参是一个巨大的优势，在同样设备的setting下)。您认为有什么更好的解决方向吗？

**Comment by Yaojie-Shen** [comment]
> > > 您好，我想请问在之前已经安装过ffmpeg的前提下，Compressed-Video-Reader/ffmpeg/install_ffmpeg.sh中的 sudo apt -y install libass-dev libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev texinfo zlib1g-dev nasm yasm libx264-dev libx265-dev libnuma-dev libvpx-dev libmp3lame-dev libopus-dev 可以注释掉吗？毕竟这个命令需要root权限
> > 
> > 
> > 不确定，可以试试…… 我还在计划着发布到pypi上（这样就不需要本地编译了），但是由于环境的问题暂时搁置了。如果是因为没有办法获得权限的话你可以试着在你有权限的linux环境下先编译出一个whl文件，正确的情况下应该会有100MB以上的大小，然后上传到你目前的系统上安装。
> 
> 好的，非常感谢您的回复。另外我想问下论文中提到的fast是指inference的时候吗？类似swinbert这种end-to-end模型，您论文中设计的模型train过程似乎并不快。使用离线特征训练模型的话，只需要预训练模型抽取一次特征，但是训练起来快很多(这对于调参是一个巨大的优势，在同样设备的setting下)。您认为有什么更好的解决方向吗？

是的，我们论文中的速度测试我们提到的都是 inference 阶段的速度。我们希望做的就是一个端到端的模型，因为预先提取特征在推理阶段会很慢（参见文中的 Table 3，我们测了特征预提取模型的速度）。

我们把 visual 特征提取的 backbone 也一起在 caption 上训练，所以确实如你所述训练速度会很慢。我们目前计划的是做一些预训练，这样就可以获得一个更加通用的压缩域上的 visual backbone，我们就可以回到预先提取特征的训练模式，或者可以用更少的训练量来 finetune 一个下游任务。

**Comment by myccver** [comment]
> > > > 您好，我想请问在之前已经安装过ffmpeg的前提下，Compressed-Video-Reader/ffmpeg/install_ffmpeg.sh中的 sudo apt -y install libass-dev libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev texinfo zlib1g-dev nasm yasm libx264-dev libx265-dev libnuma-dev libvpx-dev libmp3lame-dev libopus-dev 可以注释掉吗？毕竟这个命令需要root权限
> > > 
> > > 
> > > 不确定，可以试试…… 我还在计划着发布到pypi上（这样就不需要本地编译了），但是由于环境的问题暂时搁置了。如果是因为没有办法获得权限的话你可以试着在你有权限的linux环境下先编译出一个whl文件，正确的情况下应该会有100MB以上的大小，然后上传到你目前的系统上安装。
> > 
> > 
> > 好的，非常感谢您的回复。另外我想问下论文中提到的fast是指inference的时候吗？类似swinbert这种end-to-end模型，您论文中设计的模型train过程似乎并不快。使用离线特征训练模型的话，只需要预训练模型抽取一次特征，但是训练起来快很多(这对于调参是一个巨大的优势，在同样设备的setting下)。您认为有什么更好的解决方向吗？
> 
> 是的，我们论文中的速度测试我们提到的都是 inference 阶段的速度。我们希望做的就是一个端到端的模型，因为预先提取特征在推理阶段会很慢（参见文中的 Table 3，我们测了特征预提取模型的速度）。
> 
> 我们把 visual 特征提取的 backbone 也一起在 caption 上训练，所以确实如你所述训练速度会很慢。我们目前计划的是做一些预训练，这样就可以获得一个更加通用的压缩域上的 visual backbone，我们就可以回到预先提取特征的训练模式，或者可以用更少的训练量来 finetune 一个下游任务。

再次感谢您的回复，谢谢。
