### ISSUE TITLE
docker image?

### ISSUE THREAD

**Issue by ybsu** [AcherStyx/Compressed-Video-Reader#2]
Dear sir, I have trouble installing cv_reader, for the sake of I have not the sudo permission and my linux server cannot connect to the external network. So is there a suitable docker image or some other way  to do this (cv_reader) ?  Thank you, sir!

**Comment by Yaojie-Shen** [comment]
Hello!

Here is a compiled wheel package: [Google Drive](https://drive.google.com/file/d/1pJ-soCoSn2-ORRx8JJ-COlqs5pwGJMiF/view?usp=share_link)
This was built by running `python3 setup.py bdist_wheel` under the root folder of this project after preparing the ffmpeg. You can compile it yourself if your environment does not match mine.

To install it, run `pip3 install cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl`.

**Comment by Yaojie-Shen** [comment]
Please reopen it if you are still facing the same problem.

**Comment by ybsu** [comment]
> Hello!
> 
> Here is a compiled wheel package: [Google Drive](https://drive.google.com/file/d/1pJ-soCoSn2-ORRx8JJ-COlqs5pwGJMiF/view?usp=share_link) This was built by running `python3 setup.py bdist_wheel` under the root folder of this project after preparing the ffmpeg. You can compile it yourself if your environment does not match mine.
> 
> To install it, run `pip3 install cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl`.


Hello! Thanks for your reply, I have installed  the package in the requriement.txt and then installed cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl by `pip3 install cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl`. 
Unfortunately, when I tap "cv_reader", I got the error in the picture 1 below : "ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory";   
Second, when I  was running code: "python3 tools/video_convert.py --codec=libx264 --keyint=60 --resize=240 -i dataset/msrvtt/videos -o dataset/msrvtt/videos_h264_keyint_60" according to the Cocap/dataset/README.md, I got the error: FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg',   Any other problem with my environment?  How to fix them? Thanks, sir.
<img width="798" alt="iShot_2024-01-24_17 09 45" src="https://github.com/acherstyx/Compressed-Video-Reader/assets/38691891/c61b277c-026a-4ec2-8792-971b82e9db82">
<img width="1486" alt="iShot_2024-01-24_17 08 59" src="https://github.com/acherstyx/Compressed-Video-Reader/assets/38691891/fb159583-10ea-41c7-8488-a433c3f85d9e">

**Comment by ybsu** [comment]
Dear sir, I have solved the problem occured before using command 'conda install -c conda-forge ffmpeg';   But I met a new problem: when  I was running training procedure by "python3 mm_video/run_net.py --cfg configs/compressed_video/msrvtt_captioning.yaml" , I got error "ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/qysu/anaconda3/envs/cocap/lib/python3.9/site-packages/cv_reader/api.cpython-39-x86_64-linux-gnu.so)", what can I do to solve it? Thanks.
<img width="1505" alt="iShot_2024-01-28_21 17 00" src="https://github.com/acherstyx/Compressed-Video-Reader/assets/38691891/b0c4c677-ef7b-4152-9f3b-eb54463d2320">


> > Hello!
> > Here is a compiled wheel package: [Google Drive](https://drive.google.com/file/d/1pJ-soCoSn2-ORRx8JJ-COlqs5pwGJMiF/view?usp=share_link) This was built by running `python3 setup.py bdist_wheel` under the root folder of this project after preparing the ffmpeg. You can compile it yourself if your environment does not match mine.
> > To install it, run `pip3 install cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl`.
> 
> Hello! Thanks for your reply, I have installed the package in the requriement.txt and then installed cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl by `pip3 install cv_reader-1.1.0-cp39-cp39-linux_x86_64.whl`. Unfortunately, when I tap "cv_reader", I got the error in the picture 1 below : "ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory"; Second, when I was running code: "python3 tools/video_convert.py --codec=libx264 --keyint=60 --resize=240 -i dataset/msrvtt/videos -o dataset/msrvtt/videos_h264_keyint_60" according to the Cocap/dataset/README.md, I got the error: FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg', Any other problem with my environment? How to fix them? Thanks, sir. <img alt="iShot_2024-01-24_17 09 45" width="798" src="https://private-user-images.githubusercontent.com/38691891/299256441-c61b277c-026a-4ec2-8792-971b82e9db82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDc4MjgsIm5iZiI6MTcwNjQ0NzUyOCwicGF0aCI6Ii8zODY5MTg5MS8yOTkyNTY0NDEtYzYxYjI3N2MtMDI2YS00ZWMyLTg3OTItOTcxYjgyZTlkYjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMzc2MjQxNjM0ZGQ1MmM1Nzg3M2E5Y2Q3M2JiMjFkZjI5NWJlMDNiYjBlYmE1MWQ0ZDYxODY3MjhmNDNlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yl_qGdnzpa39jeVqrJxUG5HgjZpASjL6It6xZDT_-6c"> <img alt="iShot_2024-01-24_17 08 59" width="1486" src="https://private-user-images.githubusercontent.com/38691891/299256456-fb159583-10ea-41c7-8488-a433c3f85d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDc4MjgsIm5iZiI6MTcwNjQ0NzUyOCwicGF0aCI6Ii8zODY5MTg5MS8yOTkyNTY0NTYtZmIxNTk1ODMtMTBlYS00MWM3LTg0ODgtYTQzM2MzZjg1ZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YWRkZDljNDk2N2NkMTY1MzNhNmM1ZjhiZDk2NGEwMzI1ZGVhYmNjMWI3OGNlNWQ2ZjVlMGY2YmE5MDMxMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FGQc-DnBJk51cww5ocRn7pHbOhRF63AwLeIs-vmZXo">
