### ISSUE TITLE
residual images are not residual

### ISSUE THREAD

**Issue by jstraub** [AcherStyx/Compressed-Video-Reader#5]
Thanks for putting this nice code together :) I am trying to read out motion vectors and residual images from mp4 as well.
Following your code I can get the motion vectors just fine, but the residual images end up being just the decoded images from the video. This is useful as well to me but I really would like the residual images. 

Is there any trick to get those (you show them in your paper?). Do I need the ffmpeg patches to get them?

**Comment by Yaojie-Shen** [comment]
Hello @jstraub,

Thank you for your interest in our work! The first thing you need to know is that this reader is only for H.264/H.265 encoded videos, so you need to ensure your video is encoded with the correct encoder. For H.264 videos, we extract residuals by modifying the FFmpeg package, so there is a patch contained in `ffmpeg/ffmpeg_patch`, which can be installed through `ffmpeg/install_ffmpeg.sh`. I think you can comment out `make install` in the script, you don't need to actually install it. The `CMakeLists.txt` will point to this directory when finding the dependency.

**Comment by Yaojie-Shen** [comment]
You need to correctly point to the patched version of FFmpeg when compiling the reader.

**Comment by Yaojie-Shen** [comment]
I will close this issue. Please reopen it if you still encounter any problems.

**Comment by ThisisBillhe** [comment]
Hi Yaojie,

Thanks for your great work.

How can I modify the file to obtain both residual and original video frames simultaneously?

> Hello [@jstraub](https://github.com/jstraub),
> 
> Thank you for your interest in our work! The first thing you need to know is that this reader is only for H.264/H.265 encoded videos, so you need to ensure your video is encoded with the correct encoder. For H.264 videos, we extract residuals by modifying the FFmpeg package, so there is a patch contained in `ffmpeg/ffmpeg_patch`, which can be installed through `ffmpeg/install_ffmpeg.sh`. I think you can comment out `make install` in the script, you don't need to actually install it. The `CMakeLists.txt` will point to this directory when finding the dependency.
